	function addCompany(name,id,bannerUrl,hq,size,industry,website,photosUrl,logoUrl,title,description){
		var newComp = Object.create(Company);
		
		newComp.name = name;
		newComp.id = id;
		newComp.bannerUrl = bannerUrl;
		newComp.hq = hq;
		newComp.size = size;
		newComp.industry = industry;
		newComp.website = website;
		newComp.photosUrl = photosUrl;
		newComp.logoUrl = logoUrl;
		newComp.openPositions = [];
		newComp.title = title;
		newComp.description = description
		console.log(newComp);
		this.allCompanies.push(newComp);
	}

	function addPosition(companyName, id,title,location,description,reqs,applicantsId){
		var newPos = Object.create(Positions);
		
		newPos.id = id;
		newPos.title = title;
		newPos.location = location;
		newPos.description = description;
		newPos.reqs = reqs;
		newPos.applicantsId = applicantsId;

		for(i = 0; i < this.allCompanies.length; i++){
			if(this.allCompanies[i].name == companyName) {
				allCompanies[i].openPositions.push(newPos);
				break;
			}			
		}
	}

	function getCompany(companyName){
		for(i = 0; i < this.allCompanies.length; i++){
			if(this.allCompanies[i].name == companyName) {
				return allCompanies[i];
			}			
		}
	}

	function populateCompanies(){
		this.addCompany("Amazon, Inc.","1","amazon.PNG","Seattle, WA","75000",["E-Commerce","Cloud Computing"],"amazon.com",
			["amazon1.JPG","amazon2.JPG","amazon3.JPG","amazon4.JPG","amazon5.JPG","amazon6.JPG"],"amazon.jpg",
			"We pioneer", "We're a company of pioneers. It's our job to make bold bets, and we get our energy from inventing on behalf of customers. Success is measured against the possible, not the probable. For today’s pioneers, that’s exactly why there’s no place on Earth they’d rather build than Amazon.");
		this.addCompany("Salesforce","2","Salesforce.PNG","San Francisco, WA","10000",["Cloud Computing"],
			"Salesforce.com",["salesforce1.JPG","salesforce2.JPG","salesforce3.JPG"],"salesforce.jpg",
			"We pioneer", "We're a company of pioneers. It's our job to make bold bets, and we get our energy from inventing on behalf of customers. Success is measured against the possible, not the probable. For today’s pioneers, that’s exactly why there’s no place on Earth they’d rather build than Amazon.");

		this.addPosition("Amazon, Inc.","1","Software Development Engineer Intern","Santa Clara, CA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[3,5,6,7,10]);

		this.addPosition("Amazon, Inc.","2","Hardware Development Intern","Seattle, WA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[1,2,5,6,7]);

		this.addPosition("Amazon, Inc.","3","Data Science Intern","Santa Clara, CA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[4,10,11,12,15]);		

		this.addPosition("Amazon, Inc.","4","Visual Design Intern","Santa Clara, CA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[4,10,11,12,15]);

		this.addPosition("Amazon, Inc.","5","Machine Learning Researcher Intern","Seattle, WA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[4,10,11,12,15]);

		this.addPosition("Amazon, Inc.","6","UI/UX Design Intern","Seattle, WA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[4,10,11,12,15]);

		this.addPosition("Amazon, Inc.","7","MBA Intern (Graduate)","Seattle, WA",
			"• • **Please only apply to the one job posting location that most interests you as you consider Amazon's Software Development Engineer job opportunities through University Recruiting.***\n\nWe are hiring innovative Software Development Engineer interns into our technical development teams throughout the US. We are headquartered in Seattle, WA, but also have exciting opportunities at our offices across the US and Canada!\n\nIn the US: Austin, TX; Phoenix, AZ; Boston, MA; New York, NY; Los Angeles, CA; Irvine, CA; San Luis Obispo, CA; Santa Cruz, CA; Bay Area, CA; Madison, WI; Herndon, VA, Portland, OR, Denver, CO and growing!\n\nIn Canada, we are growing rapidly in: Vancouver, BC, Toronto, ON, and Ottawa, ON.\n\nOur interns and co-ops write real software and partner with a select group of experienced software development engineers, who both help and challenge them as they work on projects that matter to our customers. You’ll be given the opportunity to have direct impact on the evolution of Amazon's technologies and lead mission critical projects early in your career. Your design, code and raw smarts will contribute to solving some of the most complex technical challenges in the areas of distributed systems, data mining, optimization, scalability, and security-- just to name a few.\n\nMany of our technologies overlap—you’d be hard pressed to find a team that isn’t using Amazon Web Services (AWS), touching the catalogue, or iterating services to better personalize for the customer. Below is a small snapshot of potential work content provided to give you some of big ideas you could work with at Amazon."
			,"BASIC QUALIFICATIONS \n\n· Currently enrolled in a Bachelor’s or Master’s degree program in Computer Science, Computer Engineering, or related technical discipline with a focus on software development\n· Currently enrolled in university with graduation dates starting December 2018 and onward\n· Able to work full-time (40 hrs/week) for 12 consecutive weeks between May 2018 through September 2018\n\nPREFERRED QUALIFICATIONS\n\n· Graduation date between December 2018 and September 2019 \n· Strong understanding of object-oriented design, data structures, and algorithms\n· Proficient in one or more object-orientated programming languages (Java, C, C++, etc)\n· Ability to effectively articulate technical challenges and solutions\n· Adept at handling ambiguous or undefined challenges through strong problem solving abilities and effective communication\n\nAmazon is an Equal Opportunity-Affirmative Action Employer – Minority / Female / Disability / Veteran / Gender Identity / Sexual Orientation",
			[4,10,11,12,15]);
	}

	window.onload = function() {
		populateCompanies();
		addPosition(1);
		console.log(allCompanies);
		localStorage.setItem('allCompanies',JSON.stringify(allCompanies));
		console.log("Initialized local storage");
	}